language: ruby
script: rake
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
install: gem install oauth mocha
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email:
    recipients:
      - apisupport@odesk.com
    on_failure: change
